<a href="https://colab.research.google.com/github/Areej17-01/Generative-AI-LLMs-and-Transformers./blob/main/6_LLM_Mastery_Transformer_section.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install pandas==2.0.1
!pip install transformers==4.29.2

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.2/12.2 MB 25.8 MB/s eta 0:00:00
  Attempting uninstall: pandas
    Found existing installation: pandas 2.2.2
    Uninstalling pandas-2.2.2:
      Successfully uninstalled pandas-2.2.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 2.0.1 which is incompatible.
plotnine 0.14.5 requires pandas>=2.2.0, but you have pandas 2.0.1 which is incompatible.
xarray 2025.1.1 requires pandas>=2.1, but you have pandas 2.0.1 which is incompatible.
mizani 0.13.1 requires pandas>=2.2.0, but you have pandas 2.0.1 which is incompatible.
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 112.3/112.3 kB 2.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.1/7.1 MB 42.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 53.9 MB/s eta 0:00:00
  A

In [ ]:
from transformers import BertModel, AutoTokenizer
import pandas as pd

In [ ]:
model_name="bert-base-uncased"

In [ ]:

model= BertModel.from_pretrained(model_name)#from_pretrained means import weights its trained on.

/usr/local/lib/python3.11/dist-packages/huggingface_hub/file_download.py:795: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias', 'cls.seq_relationship.weight', 'cls.predictions.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [ ]:
tokenizer=AutoTokenizer.from_pretrained(model_name)#try having same or same sized tokenizer such that it wont give issue to you

/usr/local/lib/python3.11/dist-packages/huggingface_hub/file_download.py:795: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

In [ ]:
#now we are going to tokenize our text

In [ ]:
sentence="When life give you lemons, don't make lemonade"

In [ ]:
tokens=tokenizer.tokenize(sentence)

In [ ]:
tokens

['when',
 'life',
 'give',
 'you',
 'lemon',
 '##s',
 ',',
 'don',
 "'",
 't',
 'make',
 'lemon',
 '##ade']

In [ ]:
#now create a token id of vocab from tokenizer

In [ ]:
vocab=tokenizer.vocab

In [ ]:
vocab

{'soaked': 13077,
 '##gers': 15776,
 'wheeler': 12819,
 '##ts': 3215,
 'loan': 5414,
 'sulfur': 17864,
 'inline': 23881,
 'prevention': 9740,
 '##usia': 24118,
 'gora': 26967,
 'mrna': 28848,
 '##ο': 29730,
 'churches': 5231,
 'printed': 6267,
 'photographers': 17008,
 'fa': 6904,
 'transports': 19003,
 'sees': 5927,
 '##onic': 12356,
 'benevolent': 25786,
 '[unused529]': 534,
 'concern': 5142,
 '##amo': 22591,
 'wong': 11789,
 'reporters': 12060,
 'pius': 14363,
 '[unused538]': 543,
 'locked': 5299,
 'dreaming': 12802,
 '##ylus': 18871,
 'b1': 29491,
 'either': 2593,
 '[unused17]': 18,
 'metro': 6005,
 'principle': 6958,
 '2000': 2456,
 'announce': 14970,
 'ள': 1393,
 'bonnie': 12220,
 '扌': 1859,
 'au': 8740,
 'governors': 11141,
 'kia': 27005,
 'oldies': 26826,
 '128': 11899,
 'heir': 8215,
 'cosmetics': 25381,
 'ballast': 28030,
 'shitty': 28543,
 'holiness': 27692,
 '##nai': 26416,
 'muffled': 15783,
 'shoreline': 17721,
 'not': 2025,
 'informed': 6727,
 'plants': 4264,
 'athletes'

In [ ]:
vocab = tokenizer.vocab
vocab_df = pd.DataFrame({"token": vocab.keys(), "token_id": vocab.values()})
vocab_df = vocab_df.sort_values(by="token_id").set_index("token_id")

vocab_df

token
token_id           
0             [PAD]
1         [unused0]
2         [unused1]
3         [unused2]
4         [unused3]
...             ...
30517           ##．
30518           ##／
30519           ##：
30520           ##？
30521           ##～

[30522 rows x 1 columns]

In [ ]:
token_id=tokenizer.encode(sentence)
token_id

[101,
 2043,
 2166,
 2507,
 2017,
 14380,
 2015,
 1010,
 2123,
 1005,
 1056,
 2191,
 14380,
 9648,
 102]

In [ ]:
#compairing token vs encoded token_ids

In [ ]:
len(tokens),len(token_id)

(13, 15)

In [ ]:
#check which token id is mapping with which token

In [ ]:
list(zip(tokens,token_id))

[('when', 101),
 ('life', 2043),
 ('give', 2166),
 ('you', 2507),
 ('lemon', 2017),
 ('##s', 14380),
 (',', 2015),
 ('don', 1010),
 ("'", 2123),
 ('t', 1005),
 ('make', 1056),
 ('lemon', 2191),
 ('##ade', 14380)]

In [ ]:
tokenizer.decode(token_id)

"[CLS] when life give you lemons, don't make lemonade [SEP]"

In [ ]:
#now get whole output from tokenizer

In [ ]:
tokenizer_out2=tokenizer(sentence,return_tensors="pt")
tokenizer_out2

{'input_ids': tensor([[  101,  2043,  2166,  2507,  2017, 14380,  2015,  1010,  2123,  1005,
          1056,  2191, 14380,  9648,   102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}

In [ ]:
#tokenizing two sentence:

In [ ]:
sentence2 = sentence.replace("don't ", "")
sentence2

'When life give you lemons, make lemonade'

In [ ]:
tokenizer_out2 = tokenizer([sentence, sentence2], padding=True)
tokenizer_out2

{'input_ids': [[101, 2043, 2166, 2507, 2017, 14380, 2015, 1010, 2123, 1005, 1056, 2191, 14380, 9648, 102], [101, 2043, 2166, 2507, 2017, 14380, 2015, 1010, 2191, 14380, 9648, 102, 0, 0, 0]], 'token_type_ids': [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0]]}

In [ ]:
tokenizer.decode(tokenizer_out2["input_ids"][0])

"[CLS] when life give you lemons, don't make lemonade [SEP]"

In [ ]:
tokenizer.decode(tokenizer_out2["input_ids"][1])

'[CLS] when life give you lemons, make lemonade [SEP] [PAD] [PAD] [PAD]'

In [ ]:
#

#semantic understanding with bert

In [ ]:
!pip install scipy

In [ ]:
from scipy.spatial.distance import cosine

In [ ]:
#using same tokenizer and model

In [ ]:
def predict(sentence):
  encoded_input=tokenizer(sentence,return_tensors="pt")
  model_output=model(**encoded_input)[0]
  return model_output

In [ ]:
#setting up sentences

In [ ]:
# Defining the sentences
sentence1 = "There was a fly drinking from my soup"
sentence2 = "There is a fly swimming in my juice"
# sentence2 = "To become a commercial pilot, he had to fly for 1500 hours." # second fly example

# Tokenizing the sentences
tokens1 = tokenizer.tokenize(sentence1)
tokens2 = tokenizer.tokenize(sentence2)

In [ ]:
# Getting model predictions for the sentences
out1 = predict(sentence1)
out2 = predict(sentence2)

In [ ]:
out1

tensor([[[ 0.1801,  0.2148, -0.1345,  ...,  0.0341,  0.1881,  0.2848],
         [ 0.1141, -0.0924, -0.2282,  ...,  0.0836,  0.4663, -0.5944],
         [ 0.3032, -0.0386, -0.1040,  ...,  0.0578,  0.1312,  0.1196],
         ...,
         [ 0.3053, -0.2663,  0.7953,  ...,  0.0021,  0.2165, -0.1643],
         [-0.3966, -0.2276, -0.5557,  ...,  0.8573,  0.0926,  0.0289],
         [ 0.7831,  0.3995, -0.4056,  ..., -0.1326, -0.6944, -0.3361]]],
       grad_fn=<NativeLayerNormBackward0>)

In [ ]:
out2

tensor([[[ 1.8506e-01,  3.4407e-01,  1.1003e-02,  ..., -4.5318e-02,
           1.0136e-01,  3.1968e-01],
         [ 1.4597e-01,  5.9355e-01, -2.6514e-01,  ...,  7.9276e-02,
           9.4191e-01,  1.5419e-02],
         [-4.4648e-02,  3.8051e-01,  8.5061e-02,  ..., -6.1494e-02,
           3.7416e-01,  4.8411e-01],
         ...,
         [ 2.5369e-01,  7.0396e-01,  4.3559e-01,  ...,  1.7258e-02,
           2.7908e-01,  2.4147e-01],
         [ 8.7310e-02, -6.6136e-02, -4.2246e-02,  ...,  1.7052e-01,
           1.0898e-04,  1.1950e-01],
         [ 9.5383e-01,  4.7838e-01, -3.0161e-01,  ..., -2.7083e-01,
          -6.6819e-01, -4.2718e-01]]], grad_fn=<NativeLayerNormBackward0>)

In [ ]:
emb1 = out1[0:, tokens1.index("fly"), :].detach()[0]
emb2 = out2[0:, tokens2.index("fly"), :].detach()[0]

# emb1 = out1[0:, 3, :].detach()
# emb2 = out2[0:, 3, :].detach()

In [ ]:
cosine(emb1,emb2)

0.12556747052457384

In [ ]:
#sentence similarity

In [ ]:
import torch

In [ ]:
def get_sentence_embedding(sentence):
    tokens = tokenizer(sentence, return_tensors='pt', truncation=True, padding=True)
    with torch.no_grad():
        output = model(**tokens)

    cls_embedding = output.last_hidden_state[:, 0, :]  # Shape: (1, hidden_size)
    return cls_embedding.squeeze(0).numpy()

In [ ]:
# Sentences to compare
sentence1 = "The quick brown fox jumps over the lazy dog."
sentence2 = "A fast, brown animal leaps over a sleepy canine."

# Get embeddings
embedding1 = get_sentence_embedding(sentence1)
embedding2 = get_sentence_embedding(sentence2)

In [ ]:
cosine(embedding1,embedding2)

0.057655774645136826

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity


In [ ]:
similarity = cosine_similarity([embedding1], [embedding2])
print(f"Cosine Similarity: {similarity[0][0]}")

Cosine Similarity: 0.9423444271087646


#MASKED TOKENS

In [ ]:
import numpy as np
from scipy.special import softmax
from transformers import AutoModelForMaskedLM, AutoTokenizer


In [ ]:
model = AutoModelForMaskedLM.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name)

/usr/local/lib/python3.11/dist-packages/huggingface_hub/file_download.py:795: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/436M [00:00<?, ?B/s]

Some weights of the model checkpoint at bert-base-cased were not used when initializing BertForMaskedLM: ['cls.seq_relationship.weight', 'cls.seq_relationship.bias']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/213k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/436k [00:00<?, ?B/s]

In [ ]:
mask=tokenizer.mask_token #defining a mask token for prediction

In [ ]:
mask

'[MASK]'

In [ ]:
sentence= f"I want to {mask} me"

In [ ]:
tokens=tokenizer.tokenize(sentence)

In [ ]:
tokens

['I', 'want', 'to', '[MASK]', 'me']

In [ ]:
tokenize_input=tokenizer(sentence, return_tensors="pt")
output=model(**tokenize_input)
output

MaskedLMOutput(loss=None, logits=tensor([[[ -7.3789,  -7.3145,  -7.4067,  ...,  -6.1505,  -5.9793,  -6.2913],
         [ -8.0514,  -8.2956,  -8.0348,  ...,  -6.6190,  -6.5002,  -6.8498],
         [-11.6912, -11.7081, -11.2969,  ...,  -6.2796,  -6.7386,  -6.0700],
         ...,
         [ -5.3644,  -5.5553,  -5.5111,  ...,  -4.0299,  -5.1471,  -4.0135],
         [ -6.9596,  -6.8425,  -7.0064,  ...,  -4.9036,  -6.2449,  -5.4442],
         [-13.2919, -13.7697, -13.4421,  ...,  -9.3235, -12.1251, -10.8335]]],
       grad_fn=<ViewBackward0>), hidden_states=None, attentions=None)

In [ ]:
#logits: logit is for probability score of tokens that could be there


In [ ]:

# Detaching the logits from the model output and converting to numpy array
logits = output.logits.detach().numpy()[0]

In [ ]:
logits

array([[ -7.378911 ,  -7.314486 ,  -7.406709 , ...,  -6.150456 ,
         -5.979263 ,  -6.2913384],
       [ -8.051364 ,  -8.295631 ,  -8.034809 , ...,  -6.6189957,
         -6.5001593,  -6.8497605],
       [-11.691157 , -11.708065 , -11.296928 , ...,  -6.2796435,
         -6.738597 ,  -6.070003 ],
       ...,
       [ -5.3644214,  -5.5552893,  -5.51114  , ...,  -4.0299277,
         -5.1471443,  -4.013492 ],
       [ -6.959622 ,  -6.842537 ,  -7.0063505, ...,  -4.903573 ,
         -6.244861 ,  -5.4441524],
       [-13.291922 , -13.769737 , -13.442129 , ...,  -9.323456 ,
        -12.125083 , -10.83352  ]], dtype=float32)

In [ ]:
masked_logits=logits[tokens.index(mask)+1]
confidence_scores=softmax(masked_logits)

In [ ]:
confidence_scores

array([1.9824258e-08, 1.6379651e-08, 1.7118973e-08, ..., 7.5293961e-08,
       2.4635387e-08, 7.6541689e-08], dtype=float32)

In [ ]:
for i in np.argsort(confidence_scores)[::-1][:5]:
    pred_token = tokenizer.decode(i)
    score = confidence_scores[i]

    # print(pred_token, score)
    print(sentence.replace(mask, pred_token))

I want to kill me
I want to kiss me
I want to help me
I want to be me
I want to tell me


# Sematic Index and  Search:

In [1]:
# Installing the necessary libraries
!pip install datasets==2.14.0
!pip install torch[cpu]
!pip install sentence-transformers==2.2.2

In [2]:
!pip install huggingface-hub==0.25.2
!pip install --upgrade datasets


  Using cached datasets-3.2.0-py3-none-any.whl.metadata (20 kB)
Using cached datasets-3.2.0-py3-none-any.whl (480 kB)
  Attempting uninstall: datasets
    Found existing installation: datasets 2.14.0
    Uninstalling datasets-2.14.0:
      Successfully uninstalled datasets-2.14.0


In [3]:
from datasets import load_dataset
from sentence_transformers import SentenceTransformer, util
import torch
import os

In [4]:
dataset = load_dataset("multi_news", split="test")
dataset

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_token.py:90: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


Dataset({
    features: ['document', 'summary'],
    num_rows: 5622
})

In [5]:
df = dataset.to_pandas().sample(1000, random_state=42)
df

document  \
4830  Tweet with a location \n \n You can add locati...   
1255  CNN host Piers Morgan just called to discuss h...   
80    White House communications director Anthony Sc...   
3044  CLOSE Scientists say they've found archaeologi...   
4486  Click image above to view graphic \n \n Althou...   
...                                                 ...   
1025  What separates us from other primates? \n \n T...   
181   White House Honey Brown Ale, believed to be th...   
3323  Washington (CNN) President Donald Trump's atto...   
3366  August 24, 2018 Morgan Warthin , 307-344-2015 ...   
263   WASHINGTON (AP) — An odorless pesticide spraye...   

                                                summary  
4830  – Denis Finley has taken to Twitter to call Po...  
1255  – CNN's Piers Morgan thinks gun-rights propone...  
80    – New White House communications director Anth...  
3044  – Scientists say they have the first physical ...  
4486  – Scientists are calling it a breakthrough and...  
...                                                 ...  
1025  – Is the grass always greener on the other sid...  
181   – Now anyone with a home-brewing kit can drink...  
3323  – President Trump has claimed he would "love t...  
3366  – Yellowstone National Park usually sees about...  
263   – A Delaware family that became seriously ill ...  

[1000 rows x 2 columns]

In [6]:
model = SentenceTransformer("all-MiniLM-L6-v2")
model

SentenceTransformer(
  (0): Transformer({'max_seq_length': 256, 'do_lower_case': False}) with Transformer model: BertModel 
  (1): Pooling({'word_embedding_dimension': 384, 'pooling_mode_cls_token': False, 'pooling_mode_mean_tokens': True, 'pooling_mode_max_tokens': False, 'pooling_mode_mean_sqrt_len_tokens': False})
  (2): Normalize()
)

In [7]:
passage_embeddings = list(model.encode(df['summary'].to_list(), show_progress_bar=True))
passage_embeddings[0].shape

Batches:   0%|          | 0/32 [00:00<?, ?it/s]

(384,)

In [8]:
query = "Find me some articles about technology and artificial intelligence"

In [17]:
query_embedding = model.encode(query)
similarities = util.cos_sim(query_embedding, passage_embeddings)
print(len(similarities[0]))
top_indices = torch.topk(similarities.flatten(), 3).indices
top_indices

1000


tensor([616, 206, 457])

In [11]:
for i in top_indices:
  print(i.item())

616
206
457


In [15]:
similarities[:1]

tensor([[ 5.3579e-02, -3.6378e-02,  1.2565e-02,  2.7547e-03, -1.2649e-02,
          2.0153e-01, -1.1161e-03,  3.9624e-02,  1.3289e-01,  6.4966e-02,
         -2.7905e-02, -4.6053e-02,  7.9777e-02,  1.0728e-02,  1.5700e-02,
          4.1723e-02,  1.1558e-01, -5.3952e-02,  4.8510e-02,  6.0522e-02,
          5.3949e-02, -4.6577e-02,  5.3235e-02,  3.4223e-02,  1.1519e-03,
          3.2105e-02,  1.2113e-01, -3.7600e-02,  3.0647e-02,  7.6232e-03,
          4.3827e-02, -2.1540e-02, -2.0933e-02, -2.1770e-02, -1.5918e-02,
         -6.7036e-02,  1.1950e-02,  4.4220e-02, -1.7669e-04, -6.2807e-02,
         -5.5425e-04,  1.5827e-01, -1.0312e-02, -6.7653e-02, -8.7383e-02,
          5.8071e-02, -1.0913e-01,  1.6119e-02, -4.0001e-02, -8.0465e-02,
         -3.0978e-03,  5.0424e-02,  3.9057e-02,  3.2126e-02,  2.9694e-02,
          1.5701e-02, -5.5077e-02,  5.4731e-02,  1.9643e-02,  6.2254e-02,
         -7.4761e-02, -8.8587e-02, -2.2988e-02,  3.4605e-03, -3.6281e-02,
         -3.2360e-02,  9.7023e-02,  1.

In [12]:
top_relevant_passages = [df.iloc[x.item()]['summary'][:200] + "..." for x in top_indices]
top_relevant_passages

['– Ford has made another big bet on the future of self-driving cars, investing $1 billion in previously unknown startup Argo AI. "The next decade will be defined by the automation of the automobile," F...',
 "– Google has revealed the topic of the year's fastest-rising search request: Robin Williams' suicide. Reaction to his death tops this year's list, the AP reports. Some notable examples: In the first f...",
 "– One of the scientists who helped unfold the structure of DNA is putting his Nobel Prize on the auction block, and James Watson says it's because he's broke after being ostracized by the academic com..."]

In [18]:
def find_relevant_news(query):
    # Encode the query using the same model
    query_embedding = model.encode(query)

    # Calculate the cosine similarity between the query and passage embeddings
    similarities = util.cos_sim(query_embedding, passage_embeddings)

    # Get the indices of the top 3 most similar passages
    top_indices = torch.topk(similarities.flatten(), 3).indices

    # Retrieve the summaries of the top 3 passages and truncate them to 160 characters
    top_relevant_passages = [df.iloc[x.item()]["summary"][:160] + "..." for x in top_indices]

    return top_relevant_passages

In [19]:
print(find_relevant_news("Natural disasters"))
print(find_relevant_news("Law enforcement and police"))
print(find_relevant_news("Politics, diplomacy and nationalism"))

['– The tsunami that killed hundreds, possibly thousands of people after an earthquake in Indonesia on Friday was much bigger and more devastating than would norm...', '– A Haitian Red Cross official estimated today that 45,000 to 50,000 people perished in the shattering earthquake Tuesday, as President Obama pledged US support...', '– A massive 7.6 magnitude earthquake struck in the Caribbean Sea Tuesday night—but there were no immediate reports of injuries or major damage after what was on...']
['– The war of words between Chicago and the federal government over "sanctuary cities" policy is heating up. Attorney General Jeff Sessions slammed the city\'s le...', '– Greg Barnes was in a hurry to get home on Friday, so when he saw police lights behind him on State Road 332 in Muncie, Indiana, "immediately I knew I was in t...', '– "We are not thugs. We are professionals," says the leader of a black policing group, addressing a speech in which President Trump urged officers to not be "to.