<a href="https://colab.research.google.com/github/Areej17-01/Generative-AI-LLMs-and-Transformers./blob/main/6_LLM_Mastery_Transformer_section.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install pandas==2.0.1
!pip install transformers==4.29.2

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.2/12.2 MB 25.8 MB/s eta 0:00:00
  Attempting uninstall: pandas
    Found existing installation: pandas 2.2.2
    Uninstalling pandas-2.2.2:
      Successfully uninstalled pandas-2.2.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 2.0.1 which is incompatible.
plotnine 0.14.5 requires pandas>=2.2.0, but you have pandas 2.0.1 which is incompatible.
xarray 2025.1.1 requires pandas>=2.1, but you have pandas 2.0.1 which is incompatible.
mizani 0.13.1 requires pandas>=2.2.0, but you have pandas 2.0.1 which is incompatible.
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 112.3/112.3 kB 2.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.1/7.1 MB 42.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 53.9 MB/s eta 0:00:00
  A

In [3]:
from transformers import BertModel, AutoTokenizer
import pandas as pd

In [4]:
model_name="bert-base-uncased"

In [5]:

model= BertModel.from_pretrained(model_name)#from_pretrained means import weights its trained on.

/usr/local/lib/python3.11/dist-packages/huggingface_hub/file_download.py:795: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias', 'cls.seq_relationship.weight', 'cls.predictions.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [6]:
tokenizer=AutoTokenizer.from_pretrained(model_name)#try having same or same sized tokenizer such that it wont give issue to you

/usr/local/lib/python3.11/dist-packages/huggingface_hub/file_download.py:795: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

In [7]:
#now we are going to tokenize our text

In [9]:
sentence="When life give you lemons, don't make lemonade"

In [15]:
tokens=tokenizer.tokenize(sentence)

In [16]:
tokens

['when',
 'life',
 'give',
 'you',
 'lemon',
 '##s',
 ',',
 'don',
 "'",
 't',
 'make',
 'lemon',
 '##ade']

In [17]:
#now create a token id of vocab from tokenizer

In [18]:
vocab=tokenizer.vocab

In [19]:
vocab

{'soaked': 13077,
 '##gers': 15776,
 'wheeler': 12819,
 '##ts': 3215,
 'loan': 5414,
 'sulfur': 17864,
 'inline': 23881,
 'prevention': 9740,
 '##usia': 24118,
 'gora': 26967,
 'mrna': 28848,
 '##ο': 29730,
 'churches': 5231,
 'printed': 6267,
 'photographers': 17008,
 'fa': 6904,
 'transports': 19003,
 'sees': 5927,
 '##onic': 12356,
 'benevolent': 25786,
 '[unused529]': 534,
 'concern': 5142,
 '##amo': 22591,
 'wong': 11789,
 'reporters': 12060,
 'pius': 14363,
 '[unused538]': 543,
 'locked': 5299,
 'dreaming': 12802,
 '##ylus': 18871,
 'b1': 29491,
 'either': 2593,
 '[unused17]': 18,
 'metro': 6005,
 'principle': 6958,
 '2000': 2456,
 'announce': 14970,
 'ள': 1393,
 'bonnie': 12220,
 '扌': 1859,
 'au': 8740,
 'governors': 11141,
 'kia': 27005,
 'oldies': 26826,
 '128': 11899,
 'heir': 8215,
 'cosmetics': 25381,
 'ballast': 28030,
 'shitty': 28543,
 'holiness': 27692,
 '##nai': 26416,
 'muffled': 15783,
 'shoreline': 17721,
 'not': 2025,
 'informed': 6727,
 'plants': 4264,
 'athletes'

In [20]:
vocab = tokenizer.vocab
vocab_df = pd.DataFrame({"token": vocab.keys(), "token_id": vocab.values()})
vocab_df = vocab_df.sort_values(by="token_id").set_index("token_id")

vocab_df

token
token_id           
0             [PAD]
1         [unused0]
2         [unused1]
3         [unused2]
4         [unused3]
...             ...
30517           ##．
30518           ##／
30519           ##：
30520           ##？
30521           ##～

[30522 rows x 1 columns]

In [21]:
token_id=tokenizer.encode(sentence)
token_id

[101,
 2043,
 2166,
 2507,
 2017,
 14380,
 2015,
 1010,
 2123,
 1005,
 1056,
 2191,
 14380,
 9648,
 102]

In [22]:
#compairing token vs encoded token_ids

In [23]:
len(tokens),len(token_id)

(13, 15)

In [24]:
#check which token id is mapping with which token

In [25]:
list(zip(tokens,token_id))

[('when', 101),
 ('life', 2043),
 ('give', 2166),
 ('you', 2507),
 ('lemon', 2017),
 ('##s', 14380),
 (',', 2015),
 ('don', 1010),
 ("'", 2123),
 ('t', 1005),
 ('make', 1056),
 ('lemon', 2191),
 ('##ade', 14380)]

In [26]:
tokenizer.decode(token_id)

"[CLS] when life give you lemons, don't make lemonade [SEP]"

In [27]:
#now get whole output from tokenizer

In [30]:
tokenizer_out2=tokenizer(sentence,return_tensors="pt")
tokenizer_out2

{'input_ids': tensor([[  101,  2043,  2166,  2507,  2017, 14380,  2015,  1010,  2123,  1005,
          1056,  2191, 14380,  9648,   102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}

In [31]:
#tokenizing two sentence:

In [32]:
sentence2 = sentence.replace("don't ", "")
sentence2

'When life give you lemons, make lemonade'

In [33]:
tokenizer_out2 = tokenizer([sentence, sentence2], padding=True)
tokenizer_out2

{'input_ids': [[101, 2043, 2166, 2507, 2017, 14380, 2015, 1010, 2123, 1005, 1056, 2191, 14380, 9648, 102], [101, 2043, 2166, 2507, 2017, 14380, 2015, 1010, 2191, 14380, 9648, 102, 0, 0, 0]], 'token_type_ids': [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0]]}

In [34]:
tokenizer.decode(tokenizer_out2["input_ids"][0])

"[CLS] when life give you lemons, don't make lemonade [SEP]"

In [35]:
tokenizer.decode(tokenizer_out2["input_ids"][1])

'[CLS] when life give you lemons, make lemonade [SEP] [PAD] [PAD] [PAD]'

In [ ]:
#

#semantic understanding with bert

In [36]:
!pip install scipy

In [37]:
from scipy.spatial.distance import cosine

In [38]:
#using same tokenizer and model

In [39]:
def predict(sentence):
  encoded_input=tokenizer(sentence,return_tensors="pt")
  model_output=model(**encoded_input)[0]
  return model_output

In [40]:
#setting up sentences

In [41]:
# Defining the sentences
sentence1 = "There was a fly drinking from my soup"
sentence2 = "There is a fly swimming in my juice"
# sentence2 = "To become a commercial pilot, he had to fly for 1500 hours." # second fly example

# Tokenizing the sentences
tokens1 = tokenizer.tokenize(sentence1)
tokens2 = tokenizer.tokenize(sentence2)

In [42]:
# Getting model predictions for the sentences
out1 = predict(sentence1)
out2 = predict(sentence2)

In [43]:
out1

tensor([[[ 0.1801,  0.2148, -0.1345,  ...,  0.0341,  0.1881,  0.2848],
         [ 0.1141, -0.0924, -0.2282,  ...,  0.0836,  0.4663, -0.5944],
         [ 0.3032, -0.0386, -0.1040,  ...,  0.0578,  0.1312,  0.1196],
         ...,
         [ 0.3053, -0.2663,  0.7953,  ...,  0.0021,  0.2165, -0.1643],
         [-0.3966, -0.2276, -0.5557,  ...,  0.8573,  0.0926,  0.0289],
         [ 0.7831,  0.3995, -0.4056,  ..., -0.1326, -0.6944, -0.3361]]],
       grad_fn=<NativeLayerNormBackward0>)

In [45]:
out2

tensor([[[ 1.8506e-01,  3.4407e-01,  1.1003e-02,  ..., -4.5318e-02,
           1.0136e-01,  3.1968e-01],
         [ 1.4597e-01,  5.9355e-01, -2.6514e-01,  ...,  7.9276e-02,
           9.4191e-01,  1.5419e-02],
         [-4.4648e-02,  3.8051e-01,  8.5061e-02,  ..., -6.1494e-02,
           3.7416e-01,  4.8411e-01],
         ...,
         [ 2.5369e-01,  7.0396e-01,  4.3559e-01,  ...,  1.7258e-02,
           2.7908e-01,  2.4147e-01],
         [ 8.7310e-02, -6.6136e-02, -4.2246e-02,  ...,  1.7052e-01,
           1.0898e-04,  1.1950e-01],
         [ 9.5383e-01,  4.7838e-01, -3.0161e-01,  ..., -2.7083e-01,
          -6.6819e-01, -4.2718e-01]]], grad_fn=<NativeLayerNormBackward0>)

In [56]:
emb1 = out1[0:, tokens1.index("fly"), :].detach()[0]
emb2 = out2[0:, tokens2.index("fly"), :].detach()[0]

# emb1 = out1[0:, 3, :].detach()
# emb2 = out2[0:, 3, :].detach()

In [57]:
cosine(emb1,emb2)

0.12556747052457384

In [58]:
#sentence similarity

In [59]:
import torch

In [64]:
def get_sentence_embedding(sentence):
    tokens = tokenizer(sentence, return_tensors='pt', truncation=True, padding=True)
    with torch.no_grad():
        output = model(**tokens)

    cls_embedding = output.last_hidden_state[:, 0, :]  # Shape: (1, hidden_size)
    return cls_embedding.squeeze(0).numpy()

In [65]:
# Sentences to compare
sentence1 = "The quick brown fox jumps over the lazy dog."
sentence2 = "A fast, brown animal leaps over a sleepy canine."

# Get embeddings
embedding1 = get_sentence_embedding(sentence1)
embedding2 = get_sentence_embedding(sentence2)

In [66]:
cosine(embedding1,embedding2)

0.057655774645136826

In [67]:
from sklearn.metrics.pairwise import cosine_similarity


In [68]:
similarity = cosine_similarity([embedding1], [embedding2])
print(f"Cosine Similarity: {similarity[0][0]}")

Cosine Similarity: 0.9423444271087646


#MASKED TOKENS

In [87]:
import numpy as np
from scipy.special import softmax
from transformers import AutoModelForMaskedLM, AutoTokenizer


In [88]:
model = AutoModelForMaskedLM.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name)

/usr/local/lib/python3.11/dist-packages/huggingface_hub/file_download.py:795: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/436M [00:00<?, ?B/s]

Some weights of the model checkpoint at bert-base-cased were not used when initializing BertForMaskedLM: ['cls.seq_relationship.weight', 'cls.seq_relationship.bias']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/213k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/436k [00:00<?, ?B/s]

In [91]:
mask=tokenizer.mask_token #defining a mask token for prediction

In [92]:
mask

'[MASK]'

In [93]:
sentence= f"I want to {mask} me"

In [94]:
tokens=tokenizer.tokenize(sentence)

In [95]:
tokens

['I', 'want', 'to', '[MASK]', 'me']

In [96]:
tokenize_input=tokenizer(sentence, return_tensors="pt")
output=model(**tokenize_input)
output

MaskedLMOutput(loss=None, logits=tensor([[[ -7.3789,  -7.3145,  -7.4067,  ...,  -6.1505,  -5.9793,  -6.2913],
         [ -8.0514,  -8.2956,  -8.0348,  ...,  -6.6190,  -6.5002,  -6.8498],
         [-11.6912, -11.7081, -11.2969,  ...,  -6.2796,  -6.7386,  -6.0700],
         ...,
         [ -5.3644,  -5.5553,  -5.5111,  ...,  -4.0299,  -5.1471,  -4.0135],
         [ -6.9596,  -6.8425,  -7.0064,  ...,  -4.9036,  -6.2449,  -5.4442],
         [-13.2919, -13.7697, -13.4421,  ...,  -9.3235, -12.1251, -10.8335]]],
       grad_fn=<ViewBackward0>), hidden_states=None, attentions=None)

In [97]:
#logits: logit is for probability score of tokens that could be there


In [98]:

# Detaching the logits from the model output and converting to numpy array
logits = output.logits.detach().numpy()[0]

In [105]:
logits

array([[ -7.378911 ,  -7.314486 ,  -7.406709 , ...,  -6.150456 ,
         -5.979263 ,  -6.2913384],
       [ -8.051364 ,  -8.295631 ,  -8.034809 , ...,  -6.6189957,
         -6.5001593,  -6.8497605],
       [-11.691157 , -11.708065 , -11.296928 , ...,  -6.2796435,
         -6.738597 ,  -6.070003 ],
       ...,
       [ -5.3644214,  -5.5552893,  -5.51114  , ...,  -4.0299277,
         -5.1471443,  -4.013492 ],
       [ -6.959622 ,  -6.842537 ,  -7.0063505, ...,  -4.903573 ,
         -6.244861 ,  -5.4441524],
       [-13.291922 , -13.769737 , -13.442129 , ...,  -9.323456 ,
        -12.125083 , -10.83352  ]], dtype=float32)

In [102]:
masked_logits=logits[tokens.index(mask)+1]
confidence_scores=softmax(masked_logits)

In [103]:
confidence_scores

array([1.9824258e-08, 1.6379651e-08, 1.7118973e-08, ..., 7.5293961e-08,
       2.4635387e-08, 7.6541689e-08], dtype=float32)

In [104]:
for i in np.argsort(confidence_scores)[::-1][:5]:
    pred_token = tokenizer.decode(i)
    score = confidence_scores[i]

    # print(pred_token, score)
    print(sentence.replace(mask, pred_token))

I want to kill me
I want to kiss me
I want to help me
I want to be me
I want to tell me
